//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieActor
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Actor
    {
        public int IDActor { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int MovieIDMovie { get; set; }
    
        public virtual Movie Movie { get; set; }
    }
}
